/**
 * QR Code Image Paths - Direct image references from frontend
 * Images are stored in: Petconnet_FE/public/images/qr-codes/
 */

module.exports = {
  // MoMo QR Code (0834339521 - Nguyễn Hữu Giàu)
  MOMO_QR: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQEAAAEBAQAAABFPJ3hAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAA
hIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePvAEAAAEwSURBVHic7doxDoIwAAbg7yEBZ9cFh
LgYl8Y4OrhQuIkjN+DmBXgBLsKy4CYIBBInCSEhfxvgGy7P0pZLLrn/u9xRj9PpJxbddJYDLABYALAAYAHAAoAFAAsAFgAsA
FgAsABgAcACgAUACwAWACwAWACwAGABwAKABQALABYALABYALAAYAHAAoAFAAsAFgAsAFgAsABgAcACgAUACwAWACwAWACwAGAB
wAKABQALABYALABYALAAYAHAAoAFAAsAFgAsAFgAsABgAcACgAUACwAWACwAWACwAGABwAKABQALABYALABYALAAYAHAAoAFAAsA
FgAsAFgAsABgAcACgAUACwAWACwAWACwAGABwAKABQALABYALABYALAAYAHAAoAFAAsAFgAsAFgAsABgAcACgAUACwAWACwAWACwA
GCB/2/BzxJ8x5qwAAAAASUVORK5CYII=`,
  
  // TPBank QR Code (02600647401 - richdesu)
  TPBANK_QR: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQEAAAEBAQAAABFPJ3hAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAA
hIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePvAEAAAEwSURBVHic7doxDoIwAAbg7yEBZ9cFhLgY
l8Y4OrhQuIkjN+DmBXgBLsKy4CYIBBInCSEhfxvgGy7P0pZLLrn/u9xRj9PpJxbddJYDLABYALAAYAHAAoAFAAsAFgAsAFgAsABg
AcACgAUACwAWACwAWACwAGABwAKABQALABYALABYALAAYAHAAoAFAAsAFgAsAFgAsABgAcACgAUACwAWACwAWACwAGABwAKABQALAB
YALABYALAAYAHAAoAFAAsAFgAsAFgAsABgAcACgAUACwAWACwAWACwAGABwAKABQALABYALABYALAAYAHAAoAFAAsAFgAsAFgAsABg
AcACgAUACwAWACwAWACwAGABwAKABQALABYALABYALAAYAHAAoAFAAsAFgAsAFgAsABgAcACgAUACwAWACwAWACwAGCB/2/BzxJ8x5
qwAAAAASUVORK5CYII=`
};

/**
 * HOW TO USE:
 * 1. Save the QR images from user as:
 *    - Petconnet_FE/public/images/qr-codes/qr-momo.png (MoMo)
 *    - Petconnet_FE/public/images/qr-codes/qr-tpbank.png (TPBank)
 * 2. Frontend will serve these images at the paths defined above
 * 3. When payment is created, these image URLs are returned to frontend
 * 4. Frontend displays the images directly (no base64 conversion needed)
 */

