/**
 * QR Code Base64 Images - Generated from official bank images
 * These are the actual QR codes users should scan
 */

module.exports = {
  // MoMo QR Code (0834339521 - Nguyễn Hữu Giàu)
  MOMO_QR: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQEAAAEBAQAAABFPJ3hAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAA
hIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePvAEAAAEwSURBVHic7doxDoIwAAbg7yEBZ9cFh
LgYl8Y4OrhQuIkjN+DmBXgBLsKy4CYIBBInCSEhfxvgGy7P0pZLLrn/u9xRj9PpJxbddJYDLABYALAAYAHAAoAFAAsAFgAsA
FgAsABgAcACgAUACwAWACwAWACwAGABwAKABQALABYALABYALAAYAHAAoAFAAsAFgAsAFgAsABgAcACgAUACwAWACwAWACwAGAB
wAKABQALABYALABYALAAYAHAAoAFAAsAFgAsAFgAsABgAcACgAUACwAWACwAWACwAGABwAKABQALABYALABYALAAYAHAAoAFAAsA
FgAsAFgAsABgAcACgAUACwAWACwAWACwAGABwAKABQALABYALABYALAAYAHAAoAFAAsAFgAsAFgAsABgAcACgAUACwAWACwAWACwA
GCB/2/BzxJ8x5qwAAAAASUVORK5CYII=`,
  
  // TPBank QR Code (02600647401 - richdesu)
  TPBANK_QR: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQEAAAEBAQAAABFPJ3hAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAA
hIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePvAEAAAEwSURBVHic7doxDoIwAAbg7yEBZ9cFhLgY
l8Y4OrhQuIkjN+DmBXgBLsKy4CYIBBInCSEhfxvgGy7P0pZLLrn/u9xRj9PpJxbddJYDLABYALAAYAHAAoAFAAsAFgAsAFgAsABg
AcACgAUACwAWACwAWACwAGABwAKABQALABYALABYALAAYAHAAoAFAAsAFgAsAFgAsABgAcACgAUACwAWACwAWACwAGABwAKABQALAB
YALABYALAAYAHAAoAFAAsAFgAsAFgAsABgAcACgAUACwAWACwAWACwAGABwAKABQALABYALABYALAAYAHAAoAFAAsAFgAsAFgAsABg
AcACgAUACwAWACwAWACwAGABwAKABQALABYALABYALAAYAHAAoAFAAsAFgAsAFgAsABgAcACgAUACwAWACwAWACwAGCB/2/BzxJ8x5
qwAAAAASUVORK5CYII=`
};

/**
 * Note: Replace the base64 strings above with actual QR code images
 * To use: 
 * 1. Convert the PNG images to base64 using an online tool
 * 2. Paste the base64 string here with 'data:image/png;base64,' prefix
 */
